apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: obvious-moccasin-peacock
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: obvious-moccasin-peacock 
  name: obvious-moccasin-peacock
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: obvious-moccasin-peacock 
